flaskbb/flaskbb

flaskbb/management/forms.py
Passing **kwargs to category save method cases it to fail on mysql backend, as SQA strictly checks if all passed kwargs match model fields. Since value of submit button is also passed from the form and exception is raised.
Fixed by excluding 'submit' button from passed data.
=> [BUGFIX] fix category creation issue

migrations/versions/8ad96e49dc6_init.py
Varchar fields require length to be specified. 'settingsgroup' was missing this attribute, and migration failed on mysql backend.
Fixed by adding length attribute
=> [BUGFIX] fix migration for mysql 

flaskbb/forum/models.py
Category sorting on forum index view has wring sorting priority: instead of sorting by position first, it takes id first.
Fixed by swapping id and position fields in order_by
=> [BUGFIX] fix for category sorting

.travis.yml, AUTHORS, requirements.txt, setup.py, test_requirements.txt
Now possible to run tests with python setup.py test. Additional arguments can be passed to py.test with the '--pytest-args="opts"' flag. This commit also separates test requirements (py/pytest/pytest exts) from standard install requirements.
=> Add support for running tests from setup.py

flaskbb/configs/default.py
Python 3 and 2 use separate Pickle protocols. I first stumbled across this some time ago and noted it in #91. This patch changes the storage location to use the major and minor version in the storage directory. This benefits testing across multiple version than actual run time. Though, I'm sure with some prodding there could be some migration from a Python 2 install to a Python 3 install.
=> Change whoosh_index to use MajorMinor for storage directory

.travis.yml
Adding sudo: false allows us to take advantage of Travis's container architecture. I've seen test speed gains between thirty seconds and a minute on my fork.
=> Add sudo: false to use travis' container architecture

Makefile, README.md, docs/installation.rst
Updates install instructions, putting a preference towards using the `Makefile`. Closes #147 but does not fix it. For the time being use `make install` for the dependencies + guided setup, or just `make dependencies` or `pip install -r requirements.txt` for just the dependencies (this is not noted in the install docs as there's still the required database setup needed).
=> Better install instructions

flaskbb/fixtures/settings.py
This fixes issue #156 in that it makes the default when you run "make install" to be Aurora rather than the buggy Bootstrap theme.
=> fix bug in default settings - Bootstrap themes have bits missing

flaskbb/templates/layout.html
Just a simple tweak to make the default layout show the title and subtitle from the settings
=> template automatically shows site title and subtitle

docs/installation.rst
Changed `uwsgi-plugins-python` to `uwsgi-plugin-python` as the former is incorrect and fails.
=> Fixed the apt-get call for installing uWSGI

flaskbb/templates/forum/memberlist.html, flaskbb/templates/macros.html
As described in the forum (https://forums.flaskbb.org/post/162) the sorting of the member list gets lost if the users wants to see any other page of the member list except for the first page.
This PR changes the memberlist template to extract the sorting and ordering and passes it to the render_pagination macro, where these arguments are added as optional arguments. If passed, sort_by and order_by arguments get injected to the page links.
For safety reasons, sort_by is URL-escaped while order_by is passed as bool.
=> Sorting member list

flaskbb/forum/views.py, flaskbb/templates/forum/new_post.html
Closes #244: Rename topics is not possible
Add the condition to choose proper form class in forum/views.py
Render title field in template if it is necessary.
Very small improvement of template to show proper title in breadcrumbs and form header.
Also the slugs are changing properly, didn't have to do anything with them, the redirect working as it should.
P.S. I've noticed that a lot of editing actions are using create-templates. There are wrong messages in this cases. For example, in edit post the submit button says "Reply". I'll create an issue about improvement, if you don't mind
/cc @kwijybo
=> Rename topics is not possible

.gitignore
Usally the plugins of a user should not be part of the base repository. The developer of the plugin should rather create a own git repository in the plugin folder itself as the are thought to be self contained I think.
So I added a wildcard to ignore the content of the plugins directory and explicitly added the init script and the portal folder.
=> Ignore plugins in git

flaskbb/forum/models.py, flaskbb/templates/forum/forum.html
If there are new posts to a topic the users usually wants to continue
reading at the first post (s)he has not read.
Therefore the users should be redirected to the first unread post when
clicking the topic in the forum view. If there is no unread post, the
user will be send to the topic itself, i.e. the first post
=> Redirect user to first unread post of a topic

flaskbb/auth/forms.py
Users are currently able to register without accepting the terms of service. The TOS is currently auto selected but a user could deselect the box and still register. This prevents a user from registering without accepting the TOS.
=> Force users to accept TOS.

flaskbb/forum/models.py
When a user visit a forum that he never visit,
he will get a 500 error because a AttributeError:
File "./flaskbb/forum/models.py", line 344, in first_unread
filter(Post.date_created > topicsread.last_read).\
AttributeError: 'NoneType' object has no attribute 'last_read'
=> Fix a bug about show a forum list

flaskbb/configs/default.py, flaskbb/utils/populate.py, flaskbb/utils/search.py, manage.py
On my setup (fresh download of master branch on python 2.7 and windows) - the manage.py install fails 
- the whoosheer is fed a str rather than a Unicode during the interactive setup and again during the setting up of the welcome forum 
- the topic is saved before the first post is attached- so the whoosheer throws an AttributeError
the fix here works for me
Also, all email and other Celery related activity is dependent on Redis being available even if REDIS_AVAILABLE=False so this fix also disables Celery if Redis is not active
=> Whooshee breaks manage.py install

flaskbb/templates/forum/topic.html, flaskbb/templates/forum/topic_horizontal.html
changed template for topics to generate use static links to post, that
still work if posts per page changes or topics are renamed/merged or whatever
=> static post links

flaskbb/cli/commands.py
Allows selection of config from command line
=> Update commands.py with config option

flaskbb/cli/main.py
The install script offers the choice to drop an existing database first.
It then proceeds with the `upgrade` procedure. This doesn't work
(at least) for MySQL. Processing stops with an "Database not found"
error. So let's create the database first if it's missing and then
continue with upgrading.
With this change installation works for me (MariaDB 10.1).
=> [BUGFIX] Make `flaskbb install` work with MySQL

flaskbb/forum/models.py
In initial testing, I encountered an error that caused the forum view (domain/forum/:slug) to 500 as the initial thread delete got messed up. I have no been able to recreate this issue since then (and that environment is no longer accessible so I cannot revisit it -- for the record it was OSX running 3.7alpha). (see notes below).
I tested this fix under Ubuntu 16.10 + Python 3.6, but I have no reason to believe it is different under other OS/Versions combinations.
QA I performed:
1. Topic starter with report, deleted topic.
2. Reply with a report, deleted post.
3. Reply with a report, deleted topic.
4. Topic starter + reply with reports, deleted topic.
5. Topic starter with multiple reports, deleted topic.
6. Multiple topics in forum, report topic starter in first/last/middle topic, …
=> Fixes #223 Deleting Flagged Post causes 500 INTERNAL SERVER ERROR - tentative fix

.travis.yml
Despite it being released in the last 24 hours, Travis doesn't look it supports 3.6 yet. :( So I'll add another PR with that when they do add that support.
As an aside, @sh4nks how do you feel about dropping official 3.3 support? 3.3.5 was the last binary release and that was March 4th, 2014. 3.3.6 (Oct 2014) and 3.3.7 (Feb 2016) were source only releases.
=> Add 3.4 and 3.5 to travis

flaskbb/plugins/portal/templates/index.html
As the title says, in the portal plugin the "Recent Topics" box shows topics with their created time.  A couple of my site's users have suggested that might be better as the last updated time.  A genuine one-line fix, for a Friday lunchtime :-)
=> 'Recent Topics' shows last posted time, not created time

wsgi.py
Hi,
This PR changes configuration file path to be absolute.
This way application can be instantiated from outside of its directory.
Spotted it while running the app using gunicorn as a service.
Thanks
=> Fix issue with configuration file location

flaskbb/auth/forms.py
If the verification email fails for whatever reason, every time you try to resend at /auth/activate you get the 'User is already verified" flash. I have confirmed user is not verified in the database and the maintenance panel, and the user cannot log in. I hope i haven't misunderstood, but it looks like a simple logic check needs switching. This appears to work for me.
=> cannot resend verification email as says already verified

.editorconfig, .gitignore
Ignores vim generated files (because I'm a troglodyte) and adds an [editorconfig file](editorconfig.org) so files can be formatted similarly by default. I purposely left off the `max_line_length` setting since it forces a hard line wrap which is unpleasant if you're not expecting it -- I also didn't find an explicit default in any of the usual spots.
=> Editing upgrades

flaskbb/forum/models.py, flaskbb/forum/views.py, flaskbb/message/models.py, flaskbb/templates/forum/topic.html, flaskbb/templates/forum/topic_horizontal.html, flaskbb/user/models.py, flaskbb/utils/database.py, flaskbb/utils/helpers.py, flaskbb/utils/populate.py
The main benefit of this PR is that we leverage SQLAlchemy's ability to set across relationships rather than muck about with IDs. This will cut down on multiple commits to the database to handle a single `save`/`delete` event, SQLAlchemy can intelligently handle flushing these to the database in the correct order.
Couple of other things:
* `make_comparable` class decorator for entities, this allows use to say `some_post == other_post` and it will compare if the two entities are of the same type (e.g. they are both posts) and that their identities are the same (e.g. their id fields are equal).
* `real` unwraps a LocalProxy instance, this is useful when interacting with entities. I didn't find any places where it would be dangerously in and of itself (e.g. `current_user.save()`) however …
=> Update relationships rather than IDs (in most cases)

flaskbb/cli/main.py, flaskbb/cli/users.py
When installing via the CLI, it is possible to create the admin user without admin rights. Additionally if you then realise your mistake and try to edit the user in the command line it attempts to add the same user again and fails. 
You can of course add admin users subsequently from the CLI so this doesn't brick the whole installation but I think that the user created during the install script should be forced to be an admin user
=> Bug in cli

flaskbb/utils/markup.py, tests/unit/utils/test_markup.py
Catches ClassNotFound from pygments in FlaskBBRenderer::block_code and ignores it, returning unhighlighted code. Fixes #355
=> Ignore misspelled/invalid lexer names in code blocks (fixes #355)

.gitignore, flaskbb/cli/main.py, flaskbb/utils/populate.py, tests/unit/utils/test_populate.py
Fixes #345, where 'flaskbb upgrade fixture' would return the number of settings groups it touched where it should have returned the number of individual settings.
=> Make 'flaskbb upgrade fixture' return correct number of settings changed

flaskbb/app.py, flaskbb/plugins/spec.py, flaskbb/plugins/utils.py, flaskbb/templates/user/settings_layout.html, flaskbb/user/__init__.py, flaskbb/user/plugins.py, requirements.txt
Hopefully closes #368 
@djsilcock Gonna ping you here directly to take a look as well
Allows plugins to register blocks and links in the User profile settings links. Here is a screenshot with a "Some Other Settings" block registered with a link to the forum index under it -- a completely synthetic example for sure, but this is completely constructed from the plugin system.
A few changes:
1. The plugin loader will now inspect all FlaskBB modules that are loaded for hooks to be registered. Consequentially, plugins must either be explicitly imported into the `flaskbb.app` namespace directly or into a namespace that is loaded there (directly or indirectly, e.g. how `flaskbb.users` is indirectly loaded)
2. `run_hook` now accepts an `is_markup` flag to determine if it should return a `Markup` …
=> Allow plugins to register profile settings links

setup.py
It exists in requirements.txt, but not here
=> add click-log to setup.py

flaskbb/app.py, flaskbb/configs/config.cfg.template, flaskbb/configs/default.py
Configuring the default loggers using a dictConfig instead of doing it programmatically seems to be a better idea imho. @justanr thoughts?
=> Make default logging more flexible

flaskbb/app.py, flaskbb/plugins/manager.py, flaskbb/utils/translations.py, tests/conftest.py, tests/fixtures/plugin.py, tests/unit/test_pluginmanager.py, tests/unit/utils/test_translations.py
This would prevent to clutter the 'list_name', etc with all the flaskbb plugins (which are literally all flaskbb.* modules). Still needs some more work though.
=> Mark 'flaskbb.*' plugins as internal plugins

flaskbb/templates/forum/category_layout.html
There's a typo in the category layout that only has an effect if you try to change the post icon colours in the theme.
=> fix tiny typo

flaskbb/user/views.py
As it is if a user has null in their theme column in the DB it shows as "Aurora" by default, and there's no way to select null again if you want to switch back to only seeing the default theme.
This fix could be more elegant.
=> allow user to select Default theme

flaskbb/app.py, flaskbb/plugins/manager.py
The cleanest solution I came up with. This way we don't need to use a hook for registering tasks - it's enough to decorate the tasks with ``celery.task``.
=> Don't register celery tasks for disabled plugins

flaskbb/forum/views.py, flaskbb/templates/forum/topic.html
Closes #408 
There might be others lurking in the shadows, we'll just have to smash them when we find them.
To test this, I created a topic with 300+ posts and found that queries settled around 19 per topic page after this fix rather than 30+. There's some jitter because of incidental queries (topic tracker, last seen, forums/topics read, etc) but for the most part 19 was a stable number.
=> Remove n+1 queries in view topic

flaskbb/management/views.py
The settings panel shows ALL plugins as having settings when saving a settings form. This fixes that and shows only plugins that both have settings and are activated.
=> Only show activated plugins with settings

docs/hooks.rst, flaskbb/app.py, flaskbb/markup.py, flaskbb/plugins/spec.py, flaskbb/templates/forum/category_layout.html, flaskbb/templates/forum/search_result.html, flaskbb/templates/management/forums.html, flaskbb/utils/helpers.py, tests/unit/utils/test_helpers.py, tests/unit/utils/test_markup.py
One for posts and post like things, another for everything else.
I'm not a big fan of the "nonpost_" prefix on the hook and jinja filter, so suggestions welcome, otherwise this closes #379, closes #357 and affects #382
=> Implement customizable markdown renderers

flaskbb/user/models.py, tests/unit/test_forum_models.py
Due to a ``cascade="all"`` on the ``User``'s ``tracked_topics`` relationship, removing topics from the topic tracker causes them to be deleted, as of the current master.
This bug got introduced in https://github.com/flaskbb/flaskbb/commit/a55e6f71b270167960a0c2fd0cded30f78414e01, the fateful one-line change obscured by copious code reformatting. Yikes.
I'm glad it only took me a single topic wrongly deleted to catch this.
Test included.
=> Don't delete topics when they are untracked

flaskbb/__init__.py, flaskbb/app.py, flaskbb/auth/services/__init__.py, flaskbb/auth/services/authentication.py, flaskbb/auth/services/factories.py, flaskbb/auth/services/reauthentication.py, flaskbb/auth/services/registration.py, flaskbb/auth/views.py, flaskbb/cli/main.py, flaskbb/core/auth/activation.py, flaskbb/core/auth/registration.py, flaskbb/exceptions.py, flaskbb/extensions.py, flaskbb/fixtures/settings.py, flaskbb/forum/models.py, flaskbb/management/__init__.py, flaskbb/plugins/spec.py, flaskbb/plugins/utils.py, flaskbb/tokens/__init__.py, flaskbb/user/__init__.py, flaskbb/utils/database.py, flaskbb/utils/helpers.py, flaskbb/utils/populate.py, flaskbb/utils/requirements.py, tox.ini
Makes Flake8 run over the main code base as well as the tests and fixes the complaints it found, liberal use of `#noqa` when it was the cleanest way to make flake8 happy, made the official line-length 80 but we can adjust that knob as necessary. An alternative is to also install flake8-bugbear and enable it's line length fuzzing check, the [black readme](https://github.com/ambv/black) recommends this (as an aside, black is really awesome):
> If you're using Flake8, you can bump max-line-length to 88 and forget about it. Alternatively, use Bugbear's B950 warning instead of E501 and keep the max line length at 80 which you are probably already using. 
The issue with [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) is that it's 3.5+ only, so that's likely a non-starter for now.
The …
=> Make flake8 run over everything

flaskbb/auth/forms.py, flaskbb/auth/views.py, flaskbb/templates/email/activate_account.html, flaskbb/templates/email/activate_account.txt
Fixes #479 
Restores ability to activate account from form submit. Breaks account activation into two views -- one dealing with the token in the URL and one dealing with the form submit.
We should probably pick this over to the 2.0.0 branch and do a bugfix release (2.0.1)
=> Restore ability to activate account through form submit

flaskbb/configs/config.cfg.template
Gonna tag this v2.0.2 after merge. Not sure how this slipped by in the initial testing.
=> Ensure logging path is wrapped in quotes when provided

flaskbb/forum/utils.py, flaskbb/forum/views.py, tests/unit/forum/test_forum_utils.py, tox.ini
Closes #452 
Runs before requests in the forum blueprint so this comes into play before permissions are checked.
=> Force login if forum area doesn't allow guest access

flaskbb/configs/default.py
After https://github.com/celery/kombu/commit/816e3dcf346decd4d458e2a088ac7a914b48dcce, celery will retry failed connections to the broker (I think that's the correct terminology, correct me if not). Unfortunately, they don't define the maximum number of retries, meaning that if the worker isn't running, the calls will block forever.
For flaskBB, this manifests in requests to `celerystatus` never returning if celery isn't running. On a production setup, this means that every time the management panel is accessed, another worker thread dies. Eventually all worker threads are exhausted and the forum stops responding entirely.
(I assume the same is true for requests to the password reset form, but I haven't tested that.)
This patch sets the cap to 1, meaning that if the first connection …
=> Fix celery blocking thread

flaskbb/templates/user/all_posts.html, flaskbb/templates/user/all_topics.html, flaskbb/user/models.py
I was working on a 'Liked posts' feature in [one of my addons](https://github.com/micha030201/flaskbb-plugin-vanity) when I noticed a few issues in the way flaskbb handles posted content on user pages currently. This pull request is meant to fix the issues I've discovered.
A summary of changes introduced in this PR:
- make a couple of strings translatable
- fix the bug where page navigation wouldn't display if the last page had only a single post
- change sort order to put the most recent posts on the first page
- change links to lead to the post itself rather than its topic
=> Nicer posts & topics display on user pages

flaskbb/utils/translations.py
[`babel.support.Translations` is a subclass of `babel.support.NullTranslations`](https://github.com/python-babel/babel/blob/d2cf189ff0ce505b46191268c3cbdc4b130d8dd6/babel/support.py#L525), thus the `isinstance` check always returns `True` and plugin translations are never loaded.
Fixed by comparing concrete types rather than including the entire inheritance tree.
I'd love to be able to write a test for this, but it seems like there's no testing machinery in place for either plugins or translations, and I don't have it in me to create it myself.
=> Fix plugin translations never getting loaded

docs/development/hooks/template.rst, flaskbb/management/plugins.py, flaskbb/plugins/spec.py, flaskbb/templates/macros.html, flaskbb/templates/management/settings.html
This allows a plugin to add a custom link to the settings sidebar.
See the test-mail plugin for an example (https://github.com/flaskbb/flaskbb-plugins/commit/6f45c7ca912cbac3b2729afce0da31ef93855c2e).
Now I am not quite sure if that's desired because plugins can potentially abuse this hook. Maybe someone has a better idea where plugins can add custom links to the admin panel. I know that there exists the hook where additional tabs can be added but I believe that it can get very fast cluttered because it's layout is horizontal.
=> Add hook for adding custom links to the admin settings sidebar

requirements.txt, setup.py
The newest Werkzeug has some breaking changes.  While we should probably upgrade to it eventually, for now upgrading to pre-1.0 seems to work.
=> Update Werkzeug, but not to the newest

docs/index.rst
Removes a trailing slash in the link to documentation that was sending 
it to a nonexistent page instead of the correct one.
=> Fix link to documentation

flaskbb/templates/forum/report_post.html
As the [issue 605](https://github.com/flaskbb/flaskbb/issues/605) pointed out, there was a bug when we were trying to report a post. The reporting modal would pup-up but shows us a 500 server error.
It was caused due to a bad theme import in the `report_post.html` template line 12.
```jinja
{% from theme("macros.html") import render_field %}
```
If we update the import to show us the form theme, it works normally.
```jinja
{% from theme("_macros/form.html") import render_field %}
```
=> Fixed #605

docs/development/hooks/startup.rst, flaskbb/markup.py, flaskbb/plugins/spec.py, requirements.txt, tests/unit/utils/test_markup.py
mistune 2 has been released with a full plugin system. This pull request upgrades mistune in FlaskBB, refactors the user link renderer into a mistune plugin, and adds pluggy hooks to allow FlaskBB plugins to add or remove mistune plugins.
The new hooks are named `flaskbb_load_(non)post_markdown_plugins`. The hooks are passed a list of plugins that they can modify.
Adding plugins:
```python
from mistune.plugins import plugin_abbr, plugin_table
@impl
def flaskbb_load_post_markdown_plugins(plugins):
plugins.extend([plugin_abbr, plugin_table])
```
Removing plugins:
```python
from flaskbb.markup import plugin_userify
@impl
def flaskbb_load_post_markdown_plugins(plugins):
try:
plugins.remove(plugin_userify)
except ValueError:
pass
```
=> Upgrade mistune to version 2

flaskbb/management/forms.py, flaskbb/user/forms.py
The format string for the birthday field was incorrect. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value) says it's supposed to be `yyyy-mm-dd`, which agrees with with what Firefox and Chromium are sending on my machine.
The bad format meant that any attempt to update a users account details (via the admin controls or the user's own settings page) would silently do nothing if they tried to set their birthday.
This PR fixes it and makes the birthday field work.
=> Fix birthday field validation

flaskbb/themes/aurora/src/app/flaskbb.js
This requires rebuilding the theme with `npm run build` but I've left the build artefacts out of the commit as I'm unsure the process around that (and I only have pnpm on my machine right now, so my build is slightly different).
I have tested and confirmed this fixes the issue though.
=> Fix quote ajax url (fixes flaskbb/flaskbb#631)

docs/installation.rst, flaskbb/core/auth/registration.py, flaskbb/core/tokens.py, flaskbb/plugins/spec.py, tests/unit/test_forum_models.py
There are small typos in:
- docs/installation.rst
- flaskbb/core/auth/registration.py
- flaskbb/core/tokens.py
- flaskbb/plugins/spec.py
- tests/unit/test_forum_models.py
Fixes:
- Should read `validity` rather than `validatity`.
- Should read `tracker` rather than `trakcer`.
- Should read `process` rather than `proccess`.
- Should read `immediately` rather than `immediatey`.
- Should read `address` rather than `adddress`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

flaskbb/management/views.py
As of Flask 2.1, [request.get_json()](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Request.get_json) raises a 400 error if the request doesn't contain JSON.
This caused several actions to fail when applied to single IDs (a case in which it's expected for there to be no JSON.)
* DeleteUser
* BanUser
* UnbanUser
* DeleteGroup
* MarkReportRead
* DeleteReport
These have been fixed by passing `silent=True` to all `get_json()` calls, which makes it return `None` like it used to.
=> Silence `get_json` exceptions when json is optional

flaskbb/plugins/manager.py, flaskbb/themes/aurora/build_emoji_set.py, flaskbb/utils/helpers.py
**Issues reported by the Pylint tool**
- In `flaskbb/flaskbb/utils/helpers.py:469`
- Too many arguments for format string, duplicate string formatting argument 'content'.
- In `flaskbb/flaskbb/plugins/manager.py:105`
- Using deprecated method warn(), replaced with logger.warnning()
**Issues reported by the Bandit tool**
- In `flaskbb/flaskbb/themes/aurora/build_emoji_set.py:11` and `flaskbb/flaskbb/utils/helpers.py:542`
- Request call without timeout (https://bandit.readthedocs.io/en/1.7.5/plugins/b113_request_without_timeout.html)
=> Small fixes
