flaskbb/api/users.py
It was for debug, right?
If it's really needed, `from __future__ import print_function` and `print(auth.username())`. :)
=> Nuke Python3-incompatible debug print

flaskbb/templates/forum/search_result.html
this causes error when showing search result
=> missing end tag for trans in search_result.html

flaskbb/forum/views.py
#112 Fix.
Thanks Peter, it was amazing fast.
=> Fix for #112.

flaskbb/translations/zh_CN/LC_MESSAGES/messages.po
Ennn..
Maybe file `messages.pot` is outdate, so I upgrade it also.
=> Add Chinese Simplified language

flaskbb/message/forms.py, flaskbb/message/models.py
Hello, sir
Eh..Maybe this bug is hard to describe.
Assume a user create a conversation and send a message to another.
When that people received the message and try to reply it, he will find he can't reply as himself.
Just like this:
BTW: Sorry to my poorly git experience, I create a blank pull request before.
=> Fixed a bug at private message view.

flaskbb/templates/forum/topic.html
=> Add button to ban user from post

flaskbb/utils/helpers.py
if the content contain Chinese or other Non-English language, it will throw UnicodeEncodeError
=> fix UnicodeEncodeError

flaskbb/management/views.py
Allows:
* Moderators can add/remove users from their group
* Super moderators can add/remove users from *any* moderator group or their own group
* Administrators can add/remove users from *any* group
=> Fix #139 with hacky workaround

flaskbb/auth/forms.py, flaskbb/auth/views.py, flaskbb/templates/auth/register.html
Closes #141. Allows user to select from available languages at
registration and default selection is the default forum language.
=> Implement language selection on user registration

flaskbb/auth/forms.py
Just going to merge this as it's a typo fix.
=> Correct typo in password field

flaskbb/templates/email/reset_password.txt
This was surprisingly easy to track down, thankfully.
=> Fix templating error

flaskbb/auth/views.py
Now works as expected, thanks.
=> following justanr's advice, updated my pr

flaskbb/templates/layout.html, flaskbb/translations/ru/LC_MESSAGES/messages.po
=> Russian translation added

Makefile
there was a typo in the Makefile I just fixed it...
=> fixed a typo on Makefile

flaskbb/user/models.py
This will allow users posts in their profile view to be listed from newest to oldest just like topics.
=> User posts by newest to oldest

flaskbb/translations/fr/LC_MESSAGES/messages.po
Add the first french translation.
=> French translation

flaskbb/templates/forum/category_layout.html, flaskbb/templates/forum/search_result.html, flaskbb/templates/management/forums.html
Just jumped out at me for some reason.
=> Corrected a small spelling error in comments.

flaskbb/utils/database.py
Also mark entities as hashable via the cls + id combo
=> Fix non-assignment in make_comparable

flaskbb/forum/forms.py
=> Make data required in user search

flaskbb/management/forms.py
=> Require password when adding user through admin tool

flaskbb/utils/helpers.py
=> Handle bytes/unicode conversion with who is online

flaskbb/auth/forms.py, flaskbb/auth/views.py, flaskbb/forum/forms.py, flaskbb/forum/views.py, flaskbb/management/views.py, flaskbb/message/views.py, flaskbb/templates/auth/login.html, flaskbb/user/views.py, flaskbb/utils/helpers.py, tests/endtoend/test_auth_views.py, tests/endtoend/test_message_views.py
Transforms views into CBVs. This is a first pass I mostly QA'd by clicking around and doing things in (hit as many actions as I easily could).
This first pass is mostly naive and preserves as much of the original code as is reasonable. Places where there were explicit HTTP method checks were broken into separate methods, but otherwise it's largely the same. This is to ease picking out bugs and making corrections.
Next pass will better extract common behavior -- that's the motivating factor for doing this.
=> Transform to cbv

flaskbb/cli/main.py
Found why trying to reproduce a potential bug with postgres.
=> Fix typo when storing database uri

flaskbb/forum/locals.py, flaskbb/utils/requirements.py, tests/unit/test_requirements.py
Had this idea while getting my teeth worked on the other day, since it stuck with me, it must be a good one. I clicked around a bit in places that would trigger exception and nothing popped up, the only things replaced were on permissions pulling from the request view args.
=> Add helpers for current_post/topic/forum/category

docs/installation.rst, flaskbb/cli/main.py
In response to issue #329.
1.  Reorganised the instructions for installs - which included a general tidy, and a few additional comments to help windows users on their way.
2. Added a slight find/replace workaround to solve the path slashes on windows not being set right (this is existing Flask functionality)
=> Optimising Windows Install

docs/installation.rst
Code instructions were appearing as a quote
=> Neaten up code example

flaskbb/forum/views.py, flaskbb/translations/messages.pot
=> Return redirect when moving topics

flaskbb/cli/main.py, flaskbb/utils/populate.py
Fix for #363 tested with sqlite and postgres.
=> Drop tables instead of databases

flaskbb/forum/views.py
=> add self argument to TrivializeTopic::post

flaskbb/forum/views.py
Should resolve issue #404 where redirecting to specific posts in a topic fails due to integer conversion
=> cast page to int in ViewPost

flaskbb/message/views.py
=> Attach actual user objects not their IDs when resurrecting PM thread

flaskbb/forum/forms.py
Getting a 500 error trying to add new posts. This fixes it.
=> add topic to flaskbb_form_new_topic_save call

docs/accountmanagement.rst, docs/api.rst, docs/authentication.rst, docs/coreexceptions.rst, docs/hooks.rst, docs/registration.rst, docs/tokens.rst, flaskbb/auth/services/activation.py, flaskbb/auth/services/authentication.py, flaskbb/auth/services/password.py, flaskbb/auth/services/reauthentication.py, flaskbb/auth/services/registration.py, flaskbb/core/auth/activation.py, flaskbb/core/auth/authentication.py, flaskbb/core/auth/password.py, flaskbb/core/auth/registration.py, flaskbb/core/exceptions.py, flaskbb/core/tokens.py, flaskbb/plugins/spec.py
Here's some preliminary documentation for the new interfaces and some of the implementations that were created in my last few PRs. I've added them to the API section in the documentation. 
Looking at the documentation for registration, that portion of the app might need some extra love in the near future and grow some hooks to be more in-line with how authentication et. al. are handled.
But in the meantime, let's fix wording and ambiguities.
=> Iss 431 interface documentation

docs/hooks.rst, flaskbb/auth/views.py, flaskbb/core/auth/registration.py, flaskbb/plugins/spec.py
I think this is the last part of #382
=> Add hook for registration form modification

flaskbb/utils/helpers.py
=> Use IOError alias for Py2

flaskbb/cli/users.py
Wrong order of parameter for `flaskbb users update` (CLI)
=> Wrong order of parameter for "flaskbb users update" (CLI)

flaskbb/forum/models.py, flaskbb/forum/views.py, flaskbb/templates/forum/edit_forum.html, flaskbb/templates/forum/forum.html, flaskbb/templates/forum/topictracker.html, flaskbb/utils/helpers.py
This kills the n+1 query when viewing a forum.
This is the last thing I want to include in 2.0 :)
=> Kill n+1 queries in forum view

flaskbb/management/forms.py
=> Remove signature length limit in admin panel. Related to #457.

flaskbb/forum/views.py, flaskbb/templates/forum/topictracker.html
=> Fix readtracker in TopicTracker

flaskbb/templates/management/banned_users.html
=> Fix banned user pagination

docs/installation.rst, flaskbb/management/forms.py, flaskbb/templates/forum/edit_forum.html, flaskbb/templates/forum/new_post.html, flaskbb/templates/forum/search_result.html, flaskbb/templates/forum/topic.html, flaskbb/templates/forum/topic_horizontal.html, flaskbb/templates/forum/topictracker.html, flaskbb/templates/management/overview.html, flaskbb/templates/user/profile_layout.html, flaskbb/templates/user/settings_layout.html, flaskbb/translations/messages.pot
The PR consists mostly of translation related stuff like adding more translatable strings. It also adds a small but handy 'Edit' button to the users profile page if the viewing user has sufficient permissions.
=> Fixes and cleanups

flaskbb/forum/forms.py, flaskbb/forum/models.py, flaskbb/forum/views.py, flaskbb/plugins/spec.py, flaskbb/templates/auth/login.html, flaskbb/templates/forum/new_post.html, flaskbb/templates/forum/new_topic.html, flaskbb/templates/forum/topic.html
=> Make topic title editable

flaskbb/themes/aurora/src/js/editor.js
=> enable server-side preview

flaskbb/management/models.py, flaskbb/management/views.py
=> fix an extra parameter

celery_worker.py, flaskbb/app.py, flaskbb/cli/main.py, flaskbb/configs/config.cfg.template, flaskbb/configs/default.py, flaskbb/configs/testing.py, requirements.txt
Still need to fix the ``flaskbb celery`` command.
Related issue: #568
=> Upgrade Celery to 5.x
